# Here is a default config file, you can copy to streamo-config.yaml:

# Use ${SECRET_NAME} to access secrets in this config file.
secrets:
  # Secrets can be loaded from a file of key-value pairs:
  #file: secrets.yaml
  ## Secrets can be loaded from environment variables:
  #env:
  #  - "PWD"
  # Secrets can be hard-coded:
  values:
    SECRET_NAME: "hard-coded-value"

server:
  admin_host: "0.0.0.0"
  admin_port: 12888
  loopback_ports: [10000, 11000]
